<script setup lang="ts">
import {computed,onMounted,reactive,ref,watch} from 'vue'
import {useRoute} from 'vue-router'
import {ElMessage,ElMessageBox} from 'element-plus'
import {api,formatTime,fromMicro,toMicro} from './api'
const route=useRoute(),page=computed(()=>String(route.params.page||'overview'))
const titles:Record<string,string>={overview:'服务概览',models:'模型服务',providers:'后端密钥',users:'用户管理',usage:'用户用量',audit:'内容审计',logs:'运行日志',publish:'配置发布'}
const subtitles:Record<string,string>={overview:'了解当前运行状态与金额预算',models:'为 Agent 提供独立入口，统一管理后端模型与主备策略',providers:'配置后端服务地址和密钥，密钥保存后不再显示',users:'管理调用身份与统计额度，历史记录持续保留',usage:'Asia/Shanghai · 基于 Redis 账本 · Token 额度仅统计',audit:'查看请求、回复及工具调用，内容访问会记录审计',logs:'排查请求、主备切换与结算事件',publish:'保存草稿后统一发布；已开始的请求使用原配置'}
const loading=ref(false),error=ref(''),revision=ref(0),doc=ref<any>(null),overview=ref<any>(null),data=ref<any[]>([]),more=ref(false),offset=ref(0),busy=ref(false)
const dialog=ref(''),editing=ref(false),form=reactive<any>({}),oneKey=ref(''),details=ref<any>(null),detailID=ref(''),detailOpen=ref(false),diff=ref<any>(null),diffOpen=ref(false),rollback=ref(''),auditCursor=ref(''),detailContent=ref(false),operations=ref<any[]>([])
const filters=reactive({user_id:'',model:'',request_id:'',event:'',status:'',from:'',to:'',day:'',month:''})
const cfg=computed(()=>doc.value?.config||{}),providers=computed(()=>Object.entries(cfg.value.providers||{}).map(([id,v])=>({id,...v as any}))),users=computed(()=>Object.entries(cfg.value.users||{}).map(([id,v])=>({id,...v as any}))),models=computed(()=>Object.entries(cfg.value.models||{}).map(([id,v])=>({id,...v as any})))
const settings=reactive<any>({public_url:'',fallback:false,global_limit:'',agent_limits:[]})
function resetSettings(){settings.public_url=doc.value.public_url;settings.fallback=!!cfg.value.fallback?.on_key_quota_exhausted;settings.global_limit=fromMicro(cfg.value.budget.global_limit);settings.agent_limits=Object.entries(cfg.value.budget.agent_limits).map(([id,v])=>({id,value:fromMicro(v as number)}))}
async function loadDraft(){const r=await api('/draft');doc.value=r.document;revision.value=r.revision;resetSettings()}
function query(keys:string[]){const q=new URLSearchParams({limit:'50',offset:String(offset.value)});for(const k of keys){let v=(filters as any)[k];if(v){if(k==='from'||k==='to')v=String(Math.floor(new Date(v).getTime()/1000));q.set(k,v)}}return q.toString()}
async function refresh(){loading.value=true;error.value='';try{await loadDraft();if(page.value==='overview'){overview.value=await api('/overview');data.value=(await api('/usage')).data}else if(page.value==='usage'){const r=await api('/usage?'+query(['user_id','day','month']));data.value=r.data;more.value=r.has_more}else if(page.value==='audit'){const r=await api('/audit/requests?'+query(['user_id','model','status','request_id','from','to']));data.value=r.data;more.value=r.has_more}else if(page.value==='logs'){const r=await api('/logs?'+query(['user_id','model','event','request_id','from','to']));data.value=r.data;more.value=r.has_more;const ops=await api('/operations?limit=50&offset='+offset.value);operations.value=ops.data;more.value=more.value||ops.has_more}else if(page.value==='publish'){const r=await api('/versions?limit=50&offset='+offset.value);data.value=r.data;more.value=r.has_more}}catch(e){data.value=[];overview.value=null;more.value=false;error.value=(e as Error).message}finally{loading.value=false}}
watch(page,()=>{offset.value=0;data.value=[];error.value='';refresh()});onMounted(refresh)
async function perform(fn:()=>Promise<void>){busy.value=true;try{await fn()}catch(e){ElMessage.error((e as Error).message)}finally{busy.value=false}}
function candidate(c?:any){return c?{...JSON.parse(JSON.stringify(c)),input_price:fromMicro(c.input_rate),output_price:fromMicro(c.output_rate)}:{provider:'',model:'',context_tokens:4096,max_output_tokens:1024,n_max:1,input_price:'',output_price:'',price_version:'v1',capabilities:['stream','tools'],supports_stream_usage:true}}
function open(kind:string,row?:any){for(const k of Object.keys(form))delete form[k];editing.value=!!row;dialog.value=kind
 if(kind==='provider')Object.assign(form,{id:row?.id||'',base_url:row?.base_url||'',secret:'',disabled:row?.disabled||false,codes:(row?.quota_exhaustion_codes||['insufficient_quota']).join(',')})
 if(kind==='user')Object.assign(form,{id:row?.id||'',disabled:row?.disabled||false,daily_token_limit:row?.daily_token_limit??null,monthly_token_limit:row?.monthly_token_limit??null})
 if(kind==='model')Object.assign(form,{id:row?.id||'',candidates:row?row.candidates.map(candidate):[candidate()],budget:row?fromMicro(cfg.value.budget.model_limits[row.id]):''})
 if(kind==='key')Object.assign(form,{user_id:row?.id||'',agent_id:'',scopes:['chat:write','usage:read','audit:read'],agent_budget:''})
}
async function save(){await perform(async()=>{let path='',value:any={},secret='';if(dialog.value==='provider'){path='/providers/'+form.id;value={base_url:form.base_url,disabled:form.disabled,quota_exhaustion_codes:form.codes.split(',').map((s:string)=>s.trim()).filter(Boolean)};secret=form.secret}
 if(dialog.value==='user'){path='/users/'+form.id;value={daily_token_limit:form.daily_token_limit,monthly_token_limit:form.monthly_token_limit,disabled:form.disabled}}
 if(dialog.value==='model'){path='/models/'+form.id;value={budget_limit:toMicro(form.budget),candidates:form.candidates.map((c:any)=>{const v={...c,input_rate:toMicro(c.input_price),output_rate:toMicro(c.output_price)};delete v.input_price;delete v.output_price;return v})}}
 if(dialog.value==='key'){path='/keys';value={user_id:form.user_id,agent_id:form.agent_id,scopes:form.scopes};if(form.agent_id)value.agent_budget=toMicro(form.agent_budget)}
 if(!path||path.endsWith('/'))throw new Error('请填写完整名称');const r=await api(path,dialog.value==='key'?'POST':'PUT',{revision:revision.value,value,secret});form.secret='';dialog.value='';if(r.key)oneKey.value=r.key;ElMessage.success('已保存草稿，发布后生效');await refresh()})}
async function remove(kind:string,id:string){try{await ElMessageBox.confirm(kind==='keys'?'撤销该 Gateway Key？发布后新请求将被拒绝。':'删除该配置？被其他模型引用时将无法发布。','确认修改',{type:'warning'});await perform(async()=>{await api('/'+kind+'/'+id,'DELETE',{revision:revision.value,value:{}});await refresh()})}catch{}}
async function saveSettings(){await perform(async()=>{const limits:any={};for(const x of settings.agent_limits)limits[x.id]=toMicro(x.value);await api('/settings','PUT',{revision:revision.value,value:{public_url:settings.public_url,fallback:{on_key_quota_exhausted:settings.fallback},global_limit:toMicro(settings.global_limit),agent_limits:limits}});ElMessage.success('设置已保存为草稿');await refresh()})}
async function preview(version=''){await perform(async()=>{diff.value=await api('/preview'+(version?'?version='+encodeURIComponent(version):''));rollback.value=version;diffOpen.value=true})}
async function publish(){await perform(async()=>{const result=await api('/publish','POST',{revision:revision.value,version:rollback.value});diffOpen.value=false;ElMessage.success('版本已生效：'+result.version);await refresh()})}
async function validate(){await perform(async()=>{await api('/validate','POST',{});ElMessage.success('配置校验通过')})}
async function detail(id:string,content=false,append=false){await perform(async()=>{if(!append)detailContent.value=content;const q=new URLSearchParams({include_content:String(content),limit:'50'});if(append&&auditCursor.value)q.set('cursor',auditCursor.value);const r=await api('/audit/requests/'+id+'?'+q);details.value=append?{...r,events:[...details.value.events,...r.events]}:r;detailID.value=id;auditCursor.value=r.next_cursor||'';detailOpen.value=true})}
async function copy(value:string){try{await navigator.clipboard.writeText(value);ElMessage.success('已复制')}catch{ElMessage.info('浏览器未授权剪贴板，请手动复制')}}
function next(delta:number){offset.value=Math.max(0,offset.value+delta);refresh()}
function pretty(v:any){return JSON.stringify(v,null,2)}
function endpoint(id:string){return doc.value.public_url+'/models/'+id+'/v1/chat/completions'}
function callExample(id:string){return `curl '${endpoint(id)}' \\\n  -H 'Authorization: Bearer <Gateway Key>' \\\n  -H 'Content-Type: application/json' \\\n  -d '{"messages":[{"role":"user","content":"你好"}]}'`}
</script>

<template>
<section v-loading="loading">
 <header class="page-header"><div><span class="eyebrow">GATEWAY / {{page.toUpperCase()}}</span><h1>{{titles[page]||'管理控制台'}}</h1><p class="muted">{{subtitles[page]}}</p></div><div><el-tag v-if="doc" type="info">草稿 #{{revision}}</el-tag> <el-button @click="refresh">刷新</el-button></div></header>
 <el-alert v-if="error" :title="error" type="error" :closable="false" />
 <template v-if="doc">
 <template v-if="page==='overview' && overview">
  <div class="stats"><div class="stat"><label>网关状态</label><strong>{{overview.gateway.healthy?'运行正常':'依赖异常'}}</strong></div><div class="stat"><label>模型入口</label><strong>{{overview.model_count}}</strong></div><div class="stat"><label>网关用户</label><strong>{{overview.user_count}}</strong></div><div class="stat"><label>待结算尝试</label><strong>{{overview.pending_attempts}}</strong></div></div>
  <div class="panel"><h2>金额预算 <el-tag size="small" type="info">USD</el-tag></h2><el-table :data="overview.budgets"><el-table-column prop="dimension" label="维度"/><el-table-column label="总预算"><template #default="s">${{fromMicro(s.row.limit)}}</template></el-table-column><el-table-column label="已结算"><template #default="s">${{fromMicro(s.row.spent)}}</template></el-table-column><el-table-column label="已预占"><template #default="s">${{fromMicro(s.row.reserved)}}</template></el-table-column><el-table-column label="剩余"><template #default="s">${{fromMicro(s.row.remaining)}}</template></el-table-column></el-table><p class="query-note">运行版本：{{overview.config_revision}} · 预算与用户 Token 额度独立</p></div>
  <div class="panel"><h2>今日用户用量</h2><el-table :data="data"><el-table-column prop="user_id" label="用户"/><el-table-column prop="daily.prompt_tokens" label="输入 Token"/><el-table-column prop="daily.completion_tokens" label="输出 Token"/><el-table-column prop="daily.total_tokens" label="总 Token"/><el-table-column prop="daily.unknown_attempts" label="未知用量尝试"/></el-table></div>
 </template>
 <template v-if="page==='providers'"><div class="toolbar"><el-button type="primary" @click="open('provider')">新增后端密钥</el-button><span class="muted">同一后端的不同 Key 可建立为不同条目</span></div><div class="panel"><el-table :data="providers"><el-table-column prop="id" label="名称"/><el-table-column prop="base_url" label="服务根地址" min-width="200"/><el-table-column label="密钥"><template #default>已配置 · 不回显</template></el-table-column><el-table-column label="草稿状态"><template #default="s"><el-tag :type="s.row.disabled?'info':'success'">{{s.row.disabled?'已禁用':'启用'}}</el-tag></template></el-table-column><el-table-column label="操作" width="150"><template #default="s"><el-button link type="primary" @click="open('provider',s.row)">编辑</el-button><el-button link type="danger" @click="remove('providers',s.row.id)">删除</el-button></template></el-table-column></el-table></div></template>
 <template v-if="page==='models'"><div class="toolbar"><el-button type="primary" @click="open('model')">新增模型入口</el-button><span class="muted">配置将在发布后生效</span></div><div v-for="m in models" :key="m.id" class="panel"><div class="page-header"><h2>{{m.id}} <el-tag size="small">{{m.candidates.length}} 个候选</el-tag></h2><div><el-button @click="open('model',m)">编辑</el-button><el-button text type="danger" @click="remove('models',m.id)">删除</el-button></div></div><div class="copy-line"><code>{{endpoint(m.id)}}</code><el-button size="small" @click="copy(endpoint(m.id))">复制 URL</el-button></div><p class="muted">SDK Base URL：{{doc.public_url}}/models/{{m.id}}/v1 · model：{{m.id}}</p><el-table :data="m.candidates"><el-table-column label="顺序" width="70"><template #default="s">{{s.$index===0?'主用':'备用'}}</template></el-table-column><el-table-column prop="provider" label="后端"/><el-table-column prop="model" label="真实模型"/><el-table-column label="输入 / 输出价格"><template #default="s">${{fromMicro(s.row.input_rate)}} / ${{fromMicro(s.row.output_rate)}} / 百万 Token</template></el-table-column></el-table><el-collapse><el-collapse-item title="查看调用示例"><pre>{{callExample(m.id)}}</pre></el-collapse-item></el-collapse></div></template>
 <template v-if="page==='users'"><div class="toolbar"><el-button type="primary" @click="open('user')">新增用户</el-button><el-button @click="open('key')">签发 Gateway Key</el-button></div><el-alert title="Token 额度仅用于统计与查询，超额不会拦截。禁用用户、撤销 Key 均在发布后生效。" type="info" :closable="false"/><div class="panel"><el-table :data="users"><el-table-column prop="id" label="用户"/><el-table-column label="每日额度"><template #default="s">{{s.row.daily_token_limit??'不限'}}</template></el-table-column><el-table-column label="每月额度"><template #default="s">{{s.row.monthly_token_limit??'不限'}}</template></el-table-column><el-table-column label="草稿状态"><template #default="s">{{s.row.disabled?'禁用':'启用'}}</template></el-table-column><el-table-column label="操作"><template #default="s"><el-button link type="primary" @click="open('user',s.row)">编辑</el-button><el-button link @click="open('key',s.row)">签发 Key</el-button></template></el-table-column></el-table></div><div class="panel"><h2>Gateway Keys</h2><el-table :data="cfg.api_keys"><el-table-column prop="key_env" label="Key 引用" min-width="210" show-overflow-tooltip/><el-table-column prop="user_id" label="用户"/><el-table-column prop="agent_id" label="Agent"/><el-table-column label="权限" min-width="190"><template #default="s">{{s.row.scopes.join(', ')}}</template></el-table-column><el-table-column label="状态"><template #default="s">{{s.row.disabled?'已撤销':'启用'}}</template></el-table-column><el-table-column label="操作"><template #default="s"><el-button link type="danger" :disabled="s.row.disabled" @click="remove('keys',s.row.key_env)">撤销</el-button></template></el-table-column></el-table></div></template>
 <template v-if="page==='usage'"><div class="toolbar"><el-select v-model="filters.user_id" clearable placeholder="全部用户"><el-option v-for="u in users" :key="u.id" :label="u.id" :value="u.id"/></el-select><el-date-picker v-model="filters.day" type="date" value-format="YYYY-MM-DD" placeholder="今日"/><el-date-picker v-model="filters.month" type="month" value-format="YYYY-MM" placeholder="对应月份"/><el-button type="primary" @click="offset=0;refresh()">查询</el-button></div><div class="panel"><el-table :data="data"><el-table-column prop="user_id" label="用户" width="140"/><el-table-column v-for="period in ['daily','monthly']" :key="period" :label="period==='daily'?'每日用量':'每月用量'"><template #default="s"><template v-if="s.row[period].available"><strong>{{s.row[period].total_tokens.toLocaleString()}} Token</strong><p class="muted">输入 {{s.row[period].prompt_tokens}} / 输出 {{s.row[period].completion_tokens}}<br>剩余 {{s.row[period].remaining_tokens??'不限'}} · {{s.row[period].period}}</p><el-tag v-if="s.row[period].unknown_attempts||s.row[period].pending_attempts" type="warning">待结算 {{s.row[period].pending_attempts}} / 未知 {{s.row[period].unknown_attempts}}</el-tag><span v-if="s.row[period].token_limit!==null" class="muted"> {{s.row[period].remaining_is_exact?'精确':'剩余额度非精确值'}}</span></template><el-tag v-else type="info">已过保留期</el-tag></template></el-table-column></el-table></div></template>
 <template v-if="page==='audit'||page==='logs'"><div class="toolbar"><el-input v-model="filters.user_id" placeholder="用户 ID" clearable/><el-input v-model="filters.model" placeholder="模型入口" clearable/><el-input v-model="filters.request_id" placeholder="请求编号" clearable/><el-input v-if="page==='logs'" v-model="filters.event" placeholder="事件，如 fallback.selected" clearable/><el-select v-else v-model="filters.status" clearable placeholder="请求状态"><el-option v-for="s in ['completed','failed','interrupted','pending']" :key="s" :value="s"/></el-select><el-date-picker v-model="filters.from" type="datetime" placeholder="开始时间"/><el-date-picker v-model="filters.to" type="datetime" placeholder="结束时间"/><el-button type="primary" @click="offset=0;refresh()">查询</el-button></div><div class="panel"><el-table :data="data"><el-table-column label="时间" width="180"><template #default="s">{{formatTime(s.row.created||s.row.time)}}</template></el-table-column><el-table-column prop="user_id" label="用户"/><el-table-column prop="model" label="模型"/><el-table-column :prop="page==='logs'?'event':'status'" :label="page==='logs'?'事件':'状态'"/><el-table-column label="请求编号" min-width="160" show-overflow-tooltip><template #default="s">{{s.row.id||s.row.request_id||'—'}}</template></el-table-column><el-table-column label="详情" width="100"><template #default="s"><el-button v-if="page==='audit'" link type="primary" @click="detail(s.row.id)">查看</el-button><el-popover v-else trigger="click" :width="650"><template #reference><el-button link>展开</el-button></template><pre>{{pretty(s.row)}}</pre></el-popover></template></el-table-column></el-table></div><div v-if="page==='logs'" class="panel"><h2>管理员操作审计</h2><el-table :data="operations"><el-table-column label="时间"><template #default="s">{{formatTime(s.row.time)}}</template></el-table-column><el-table-column prop="event" label="操作"/><el-table-column prop="target" label="对象" show-overflow-tooltip/><el-table-column prop="result" label="结果"/></el-table></div></template>
 <template v-if="page==='publish'"><div class="panel"><h2>网关设置 <el-tag type="warning" size="small">草稿</el-tag></h2><el-form label-position="top"><div class="form-grid"><el-form-item label="网关公开地址（用于生成调用示例）"><el-input v-model="settings.public_url" /></el-form-item><el-form-item label="全局金额预算 / USD"><el-input v-model="settings.global_limit" /></el-form-item></div><el-form-item label="API Key 额度耗尽自动切换"><el-switch v-model="settings.fallback"/><span class="muted">　仅明确额度耗尽触发，最多两个候选；已输出的流式响应不切换</span></el-form-item><div class="form-grid"><el-form-item v-for="a in settings.agent_limits" :key="a.id" :label="'Agent '+a.id+' 金额预算 / USD'"><el-input v-model="a.value"/></el-form-item></div><el-button :loading="busy" @click="saveSettings">保存设置草稿</el-button></el-form></div><div class="toolbar"><el-button :loading="busy" @click="validate">校验草稿</el-button><el-button type="primary" :loading="busy" @click="preview()">预览并发布</el-button><span class="muted">发布会平滑重载，不重置用量与预算账本</span></div><div class="panel"><h2>版本历史</h2><el-table :data="data"><el-table-column prop="id" label="版本" min-width="200" show-overflow-tooltip/><el-table-column label="创建时间" width="190"><template #default="s">{{formatTime(s.row.created)}}</template></el-table-column><el-table-column prop="status" label="状态"/><el-table-column prop="error" label="异常"/><el-table-column label="操作"><template #default="s"><el-button link :disabled="s.row.status==='active'||busy" @click="preview(s.row.id)">预览回滚</el-button></template></el-table-column></el-table></div></template>
 <div v-if="['usage','audit','logs','publish'].includes(page)" class="pagination"><el-button :disabled="offset===0" @click="next(-50)">上一页</el-button><span class="muted">第 {{offset/50+1}} 页</span><el-button :disabled="!more" @click="next(50)">下一页</el-button></div>
 </template>
</section>

<el-dialog :model-value="!!dialog" :title="({provider:'后端密钥',model:'模型入口',user:'网关用户',key:'签发 Gateway Key'} as any)[dialog]" width="760px" @close="dialog='';form.secret=''" destroy-on-close>
 <el-form label-position="top" @submit.prevent="save">
  <el-form-item v-if="dialog!=='key'" label="名称（字母、数字、下划线或短横线）"><el-input v-model="form.id" :disabled="editing" aria-label="名称"/></el-form-item>
  <template v-if="dialog==='provider'"><el-form-item label="后端服务根地址"><el-input v-model="form.base_url" placeholder="https://llm.example.com" aria-label="后端地址"/></el-form-item><p class="muted">最终请求地址：{{(form.base_url||'').replace(/\/$/,'')}}/v1/chat/completions</p><el-form-item :label="editing?'替换 API Key（留空保留原值）':'API Key'"><el-input v-model="form.secret" type="password" show-password autocomplete="new-password" aria-label="API Key"/></el-form-item><el-form-item label="额度耗尽错误码（逗号分隔）"><el-input v-model="form.codes"/></el-form-item><el-checkbox v-model="form.disabled">禁用此后端</el-checkbox></template>
  <template v-if="dialog==='user'"><div class="form-grid"><el-form-item label="每日 Token 额度（空为不限）"><el-input-number v-model="form.daily_token_limit" :min="0" :precision="0" :controls="false"/></el-form-item><el-form-item label="每月 Token 额度（空为不限）"><el-input-number v-model="form.monthly_token_limit" :min="0" :precision="0" :controls="false"/></el-form-item></div><el-checkbox v-model="form.disabled">禁用用户及其全部 Key</el-checkbox></template>
  <template v-if="dialog==='model'"><el-form-item label="此逻辑模型金额预算 / USD"><el-input v-model="form.budget" aria-label="模型预算"/></el-form-item><div v-for="(c,i) in form.candidates" :key="i" class="candidate"><div class="toolbar"><strong>{{i===0?'主用后端':'备用后端'}}</strong><el-button v-if="i>0" text type="danger" @click="form.candidates.splice(i,1)">移除备用</el-button></div><div class="form-grid"><el-form-item label="后端密钥条目"><el-select v-model="c.provider" aria-label="后端密钥条目"><el-option v-for="p in providers" :key="p.id" :value="p.id" :label="p.id" :disabled="p.disabled"/></el-select></el-form-item><el-form-item label="后端真实模型名"><el-input v-model="c.model" aria-label="真实模型名"/></el-form-item><el-form-item label="上下文 Token 上限"><el-input-number v-model="c.context_tokens" :min="1" :precision="0"/></el-form-item><el-form-item label="输出 Token 上限"><el-input-number v-model="c.max_output_tokens" :min="1" :precision="0"/></el-form-item><el-form-item label="输入价格 / USD 每百万 Token"><el-input v-model="c.input_price" aria-label="输入价格"/></el-form-item><el-form-item label="输出价格 / USD 每百万 Token"><el-input v-model="c.output_price" aria-label="输出价格"/></el-form-item><el-form-item label="最多生成数量 n"><el-input-number v-model="c.n_max" :min="1" :precision="0"/></el-form-item><el-form-item label="价格版本"><el-input v-model="c.price_version"/></el-form-item></div><el-checkbox-group v-model="c.capabilities"><el-checkbox value="stream">流式输出</el-checkbox><el-checkbox value="tools">工具调用</el-checkbox></el-checkbox-group><el-checkbox v-model="c.supports_stream_usage">支持流式 usage 统计</el-checkbox></div><el-button v-if="form.candidates?.length<2" @click="form.candidates.push(candidate())">添加备用候选</el-button></template>
  <template v-if="dialog==='key'"><el-form-item label="用户"><el-select v-model="form.user_id"><el-option v-for="u in users" :key="u.id" :value="u.id"/></el-select></el-form-item><el-form-item label="Agent ID（可选，工具执行上报需要）"><el-input v-model="form.agent_id"/></el-form-item><el-form-item v-if="form.agent_id" label="新 Agent 金额预算 / USD（已有 Agent 保留当前预算）"><el-input v-model="form.agent_budget"/></el-form-item><el-form-item label="权限"><el-checkbox-group v-model="form.scopes"><el-checkbox v-for="s in ['chat:write','usage:read','audit:read','audit:write']" :key="s" :value="s">{{s}}</el-checkbox></el-checkbox-group></el-form-item></template>
 </el-form><template #footer><el-button @click="dialog=''">取消</el-button><el-button type="primary" :loading="busy" @click="save">保存草稿</el-button></template>
</el-dialog>
<el-dialog :model-value="!!oneKey" title="请保存新 Gateway Key" @close="oneKey=''" width="650px"><el-alert title="仅此次展示。关闭后无法查看原值，发布配置后才能用于调用。" type="warning" :closable="false"/><pre class="key-once">{{oneKey}}</pre><el-button @click="copy(oneKey)">复制 Key</el-button></el-dialog>
<el-dialog v-model="diffOpen" :title="rollback?'确认回滚配置':'预览配置发布'" width="90%"><el-alert v-if="rollback" title="回滚会恢复该版本的用户与 Key 状态，可能重新启用此前禁用的凭证。" type="warning" :closable="false"/><p class="muted">仅展示配置与密钥引用，不包含密钥值。请检查用户状态、候选顺序和金额预算。</p><div v-if="diff" class="split"><div><h2>当前生效</h2><pre>{{pretty(diff.before)}}</pre></div><div><h2>{{rollback?'回滚目标':'待发布草稿'}}</h2><pre>{{pretty(diff.after)}}</pre></div></div><template #footer><el-button @click="diffOpen=false">取消</el-button><el-button type="primary" :loading="busy" @click="publish">{{rollback?'确认回滚':'确认发布'}}</el-button></template></el-dialog>
<el-drawer v-model="detailOpen" title="请求审计详情" size="75%"><template v-if="details"><div class="toolbar"><el-tag>{{details.request.capture_state}}</el-tag><el-tag type="info">{{details.request.status}}</el-tag><el-button :loading="busy" @click="detail(detailID,true)">读取请求与回复内容</el-button></div><pre>{{pretty(details.request)}}</pre><h2>尝试与事件</h2><div v-for="e in details.events" :key="e.seq" class="detail-event"><h4>{{e.type}}</h4><span class="muted">{{e.source==='agent_reported'?'Agent 上报':'网关观察'}} · {{e.attempt_id||'请求级事件'}} · 内容状态：{{e.payload_state}}</span><pre>{{pretty(e.meta)}}</pre><pre v-if="e.payload">{{pretty(e.payload)}}</pre></div><el-button v-if="auditCursor" :loading="busy" @click="detail(detailID,detailContent,true)">加载后续事件</el-button><h2>工具调用</h2><pre>{{pretty(details.tool_calls)}}</pre><p class="muted">{{details.summary_note}}</p></template></el-drawer>
</template>


